#!/usr/bin/env node

/**
 * create-launchkit — stack setup wizard for LaunchKit Pro
 *
 * Usage (from inside a cloned LaunchKit project):
 *   npx create-launchkit@latest
 *
 * Detects the LaunchKit project root, walks through stack configuration,
 * writes launchkit.config.ts + .env.local, and applies code scaffolding
 * for alternative auth (NextAuth) or database (Supabase) choices.
 *
 * https://getlaunchkit.app
 */

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import chalk from "chalk";
import ora from "ora";
import prompts from "prompts";

import {
  promptStack,
  generateConfigFile,
  generateEnvExample,
  printSetupInstructions,
  getEnvVarsForStack,
  getAIEnvVar,
  AI_PROVIDERS,
  type StackSelection,
} from "./stack-prompts";
import {
  applySupabaseScaffold,
  printSupabaseResults,
} from "./scaffolders/supabase";
import {
  applyNextAuthScaffold,
  printNextAuthResults,
  generateNextAuthClaudePrompt,
} from "./scaffolders/nextauth";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_JSON = JSON.parse(
  fs.readFileSync(path.join(__dirname, "../package.json"), "utf-8")
) as { version: string };
const VERSION = PKG_JSON.version;

const LAUNCHKIT_PURCHASE_URL = "https://getlaunchkit.app";
const LAUNCHKIT_DOCS_URL = "https://getlaunchkit.app/docs";
const LAUNCHKIT_REPO_URL = "https://github.com/People-In-Tech/launchkit-pro";

// ---------------------------------------------------------------------------
// Banner
// ---------------------------------------------------------------------------

function printBanner(): void {
  const rows = [
    "  ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗██╗  ██╗██╗████████╗",
    "  ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██║ ██╔╝██║╚══██╔══╝",
    "  ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╔╝ ██║   ██║   ",
    "  ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔═██╗ ██║   ██║   ",
    "  ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║██║  ██╗██║   ██║   ",
    "  ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝   ╚═╝  ",
  ];

  const colors = [
    chalk.hex("#818cf8"),
    chalk.hex("#a5b4fc"),
    chalk.hex("#67e8f9"),
    chalk.hex("#22d3ee"),
    chalk.hex("#06b6d4"),
    chalk.hex("#0891b2"),
  ];

  console.log();
  rows.forEach((row, i) => console.log(colors[i].bold(row)));
  console.log();
  console.log(
    `  ${chalk.hex("#818cf8")("🚀")} ` +
      chalk.white.bold("Ship your SaaS this weekend.") +
      "  " +
      chalk.dim(`v${VERSION}`)
  );
  console.log(chalk.dim("  " + "─".repeat(72)));
  console.log();
}

// ---------------------------------------------------------------------------
// Project detection
// ---------------------------------------------------------------------------

/**
 * Walks up from startDir looking for a launchkit.config.ts or
 * a package.json whose `name` includes "launchkit".
 * Returns the root directory if found, null otherwise.
 */
function findLaunchKitRoot(startDir: string): string | null {
  let dir = startDir;
  for (let i = 0; i < 5; i++) {
    if (fs.existsSync(path.join(dir, "launchkit.config.ts"))) {
      return dir;
    }
    // Check root package.json name
    const pkgPath = path.join(dir, "package.json");
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as {
          name?: string;
        };
        if (pkg.name && /launchkit/i.test(pkg.name)) {
          return dir;
        }
      } catch {
        // ignore parse errors
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break; // filesystem root
    dir = parent;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Env file writer — fully dynamic based on stack selection
// ---------------------------------------------------------------------------

function writeDynamicEnvFile(
  projectRoot: string,
  stack: StackSelection,
  envValues: Record<string, string>
): void {
  const envLocalPath = path.join(projectRoot, "apps/web/.env.local");
  const lines: string[] = [
    "# Generated by create-launchkit",
    "# https://getlaunchkit.app",
    "",
  ];

  // ── Database ───────────────────────────────────────────────────────────────
  switch (stack.database) {
    case "neon":
      lines.push(
        "# ── Database (Neon) ────────────────────────────────────────────────────────",
        `DATABASE_URL=${envValues["DATABASE_URL"] ?? ""}`,
        ""
      );
      break;
    case "supabase":
      lines.push(
        "# ── Database (Supabase) ────────────────────────────────────────────────────",
        `SUPABASE_URL=${envValues["SUPABASE_URL"] ?? ""}`,
        `SUPABASE_ANON_KEY=${envValues["SUPABASE_ANON_KEY"] ?? ""}`,
        `SUPABASE_SERVICE_ROLE_KEY=${envValues["SUPABASE_SERVICE_ROLE_KEY"] ?? ""}`,
        "# Direct connection URL for Drizzle migrations (not the pooler URL):",
        `SUPABASE_DB_URL=${envValues["SUPABASE_DB_URL"] ?? ""}`,
        ""
      );
      break;
  }

  // ── Auth ──────────────────────────────────────────────────────────────────
  switch (stack.auth) {
    case "clerk":
      lines.push(
        "# ── Auth (Clerk) ───────────────────────────────────────────────────────────",
        `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${envValues["NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"] ?? ""}`,
        `CLERK_SECRET_KEY=${envValues["CLERK_SECRET_KEY"] ?? ""}`,
        `CLERK_WEBHOOK_SECRET=${envValues["CLERK_WEBHOOK_SECRET"] ?? ""}`,
        "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/auth/sign-in",
        "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/auth/sign-up",
        "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard",
        "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard",
        ""
      );
      break;
    case "supabase":
      lines.push(
        "# ── Auth (Supabase — uses SUPABASE_URL and SUPABASE_ANON_KEY above) ─────────",
        ""
      );
      break;
    case "nextauth":
      lines.push(
        "# ── Auth (NextAuth v5) ──────────────────────────────────────────────────────",
        `AUTH_SECRET=${envValues["AUTH_SECRET"] ?? ""}`,
        `AUTH_GITHUB_ID=${envValues["AUTH_GITHUB_ID"] ?? ""}`,
        `AUTH_GITHUB_SECRET=${envValues["AUTH_GITHUB_SECRET"] ?? ""}`,
        `AUTH_GOOGLE_ID=${envValues["AUTH_GOOGLE_ID"] ?? ""}`,
        `AUTH_GOOGLE_SECRET=${envValues["AUTH_GOOGLE_SECRET"] ?? ""}`,
        "NEXTAUTH_URL=http://localhost:3000",
        ""
      );
      break;
  }

  // ── Payments ──────────────────────────────────────────────────────────────
  switch (stack.payments) {
    case "stripe":
      lines.push(
        "# ── Payments (Stripe) ──────────────────────────────────────────────────────",
        `STRIPE_SECRET_KEY=${envValues["STRIPE_SECRET_KEY"] ?? ""}`,
        `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${envValues["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"] ?? ""}`,
        `STRIPE_WEBHOOK_SECRET=${envValues["STRIPE_WEBHOOK_SECRET"] ?? ""}`,
        "STRIPE_SOLO_PRICE_ID=",
        "STRIPE_TEAMS_PRICE_ID=",
        ""
      );
      break;
    case "lemonsqueezy":
      lines.push(
        "# ── Payments (Lemon Squeezy) ────────────────────────────────────────────────",
        `LEMONSQUEEZY_API_KEY=${envValues["LEMONSQUEEZY_API_KEY"] ?? ""}`,
        `LEMONSQUEEZY_STORE_ID=${envValues["LEMONSQUEEZY_STORE_ID"] ?? ""}`,
        `LEMONSQUEEZY_WEBHOOK_SECRET=${envValues["LEMONSQUEEZY_WEBHOOK_SECRET"] ?? ""}`,
        ""
      );
      break;
    case "paddle":
      lines.push(
        "# ── Payments (Paddle) ──────────────────────────────────────────────────────",
        `PADDLE_API_KEY=${envValues["PADDLE_API_KEY"] ?? ""}`,
        `PADDLE_WEBHOOK_SECRET=${envValues["PADDLE_WEBHOOK_SECRET"] ?? ""}`,
        "PADDLE_ENVIRONMENT=sandbox",
        ""
      );
      break;
  }

  // ── AI provider ───────────────────────────────────────────────────────────
  const aiMeta = AI_PROVIDERS[stack.aiProvider];
  lines.push(`# ── AI (${aiMeta.label}) ${"─".repeat(Math.max(0, 68 - aiMeta.label.length))}`);
  const aiKey = getAIEnvVar(stack.aiProvider);
  lines.push(
    `${aiKey.key}=${envValues[aiKey.key] ?? ""}`,
    `AI_DEFAULT_PROVIDER=${stack.aiProvider}`,
    `AI_DEFAULT_MODEL=${aiMeta.defaultModel ?? ""}`,
    ""
  );

  // ── Storage ───────────────────────────────────────────────────────────────
  lines.push(
    "# ── Storage ────────────────────────────────────────────────────────────────",
    `STORAGE_PROVIDER=${stack.storageProvider}`,
    `BLOB_READ_WRITE_TOKEN=${envValues["BLOB_READ_WRITE_TOKEN"] ?? ""}`,
    ""
  );

  // ── Email ─────────────────────────────────────────────────────────────────
  if (stack.email) {
    lines.push(
      `# ── Email (${stack.email === "resend" ? "Resend" : "Postmark"}) ─────────────────────────────────────────────────────────────`,
      stack.email === "resend"
        ? `RESEND_API_KEY=${envValues["RESEND_API_KEY"] ?? ""}`
        : `POSTMARK_API_TOKEN=${envValues["POSTMARK_API_TOKEN"] ?? ""}`,
      `EMAIL_FROM=My App <hello@yourdomain.com>`,
      ""
    );
  }

  // ── PostHog ───────────────────────────────────────────────────────────────
  lines.push(
    "# ── Analytics (PostHog) ────────────────────────────────────────────────────",
    `NEXT_PUBLIC_POSTHOG_KEY=${envValues["NEXT_PUBLIC_POSTHOG_KEY"] ?? ""}`,
    "NEXT_PUBLIC_POSTHOG_HOST=https://app.posthog.com",
    ""
  );

  // ── App ───────────────────────────────────────────────────────────────────
  lines.push(
    "# ── App ────────────────────────────────────────────────────────────────────",
    `NEXT_PUBLIC_APP_URL=${envValues["NEXT_PUBLIC_APP_URL"] ?? "http://localhost:3000"}`,
    `NEXT_PUBLIC_APP_NAME=My SaaS App`,
    ""
  );

  // Ensure directory exists (apps/web may not be the CWD)
  const envDir = path.dirname(envLocalPath);
  if (!fs.existsSync(envDir)) {
    // Fallback: write to project root
    const rootEnvPath = path.join(projectRoot, ".env.local");
    fs.writeFileSync(rootEnvPath, lines.join("\n") + "\n", "utf-8");
    return;
  }

  fs.writeFileSync(envLocalPath, lines.join("\n") + "\n", "utf-8");
}

// ---------------------------------------------------------------------------
// Command runner
// ---------------------------------------------------------------------------

function runCommand(
  cmd: string,
  args: string[],
  cwd: string
): Promise<{ ok: boolean; output: string }> {
  return new Promise((resolve) => {
    let output = "";
    const proc = spawn(cmd, args, { cwd, shell: true });
    proc.stdout.on("data", (d: Buffer) => { output += d.toString(); });
    proc.stderr.on("data", (d: Buffer) => { output += d.toString(); });
    proc.on("close", (code) => { resolve({ ok: code === 0, output }); });
  });
}

// ---------------------------------------------------------------------------
// Parse CLI flags
// ---------------------------------------------------------------------------

interface CLIFlags {
  db?: string;
  auth?: string;
  payments?: string;
  help?: boolean;
}

function parseFlags(): CLIFlags {
  const flags: CLIFlags = {};
  for (const arg of process.argv.slice(2)) {
    if (arg === "--help" || arg === "-h") { flags.help = true; continue; }
    const [key, val] = arg.replace(/^--/, "").split("=");
    if (key === "db" || key === "database") flags.db = val;
    if (key === "auth") flags.auth = val;
    if (key === "payments" || key === "billing") flags.payments = val;
  }
  return flags;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  printBanner();

  const flags = parseFlags();

  if (flags.help) {
    console.log(chalk.white("Usage:") + "  " + chalk.cyan("npx create-launchkit@latest") + chalk.gray(" [options]"));
    console.log();
    console.log(chalk.gray("  Run from inside a cloned LaunchKit project to configure your stack."));
    console.log();
    console.log(chalk.bold("  Options:"));
    console.log(chalk.gray("    --db=<neon|supabase>                Database provider"));
    console.log(chalk.gray("    --auth=<clerk|nextauth|supabase>    Auth provider"));
    console.log(chalk.gray("    --payments=<stripe|lemonsqueezy>    Payments provider"));
    console.log();
    console.log(chalk.bold("  Example:"));
    console.log("    " + chalk.cyan("npx create-launchkit@latest --db=neon --auth=clerk --payments=stripe"));
    console.log();
    process.exit(0);
  }

  // ── Detect project ────────────────────────────────────────────────────────
  const projectRoot = findLaunchKitRoot(process.cwd());

  if (!projectRoot) {
    console.log(chalk.yellow("  ⚠  LaunchKit project not found.\n"));
    console.log(
      "  This wizard must be run from inside a cloned LaunchKit project.\n"
    );
    console.log(chalk.bold("  Get started:"));
    console.log(
      `  ${chalk.gray("1. Purchase →")} ${chalk.underline.cyan(LAUNCHKIT_PURCHASE_URL)}`
    );
    console.log(
      `  ${chalk.gray("2. Clone →")}    ${chalk.cyan(`git clone ${LAUNCHKIT_REPO_URL} my-app`)}`
    );
    console.log(
      `  ${chalk.gray("3. Setup →")}    ${chalk.cyan("cd my-app && npx create-launchkit@latest")}`
    );
    console.log();
    console.log(
      `  ${chalk.gray("Docs:")} ${chalk.underline(LAUNCHKIT_DOCS_URL)}`
    );
    console.log();
    process.exit(0);
  }

  const relRoot = path.relative(process.cwd(), projectRoot) || ".";
  console.log(
    `  ${chalk.green("✔")} LaunchKit project found ${chalk.gray(`(${relRoot})`)}`
  );

  // Read current config if present
  const configPath = path.join(projectRoot, "launchkit.config.ts");
  const hasExistingConfig = fs.existsSync(configPath);
  if (hasExistingConfig) {
    console.log(`  ${chalk.gray("ℹ")} Existing config found — your choices below will overwrite it.`);
  }
  console.log();

  // ── Stack selection ───────────────────────────────────────────────────────
  const stack = await promptStack(flags);

  // ── Write launchkit.config.ts ─────────────────────────────────────────────
  console.log();
  const configSpinner = ora("Writing launchkit.config.ts…").start();
  try {
    fs.writeFileSync(configPath, generateConfigFile(stack), "utf-8");
    configSpinner.succeed("launchkit.config.ts written");
  } catch (err) {
    configSpinner.fail("Failed to write launchkit.config.ts");
    console.error(err);
  }

  // ── Also write .env.example at project root ───────────────────────────────
  const envExamplePath = path.join(projectRoot, ".env.example");
  try {
    fs.writeFileSync(envExamplePath, generateEnvExample(stack), "utf-8");
  } catch {
    // non-fatal
  }

  // ── Apply Supabase scaffolding ─────────────────────────────────────────────
  if (stack.database === "supabase") {
    console.log();
    console.log(chalk.bold("  Applying Supabase patches…"));
    const supabaseResults = applySupabaseScaffold(projectRoot);
    printSupabaseResults(supabaseResults);
  }

  // ── Apply NextAuth scaffolding ─────────────────────────────────────────────
  if (stack.auth === "nextauth") {
    console.log();
    console.log(chalk.bold("  Scaffolding NextAuth v5 files…"));
    const nextAuthResults = applyNextAuthScaffold(projectRoot);
    printNextAuthResults(nextAuthResults);
    console.log();
    console.log(
      chalk.yellow("  ⚠  NextAuth requires additional migration steps.")
    );
    console.log(
      chalk.gray(
        "  Open NEXTAUTH_MIGRATION_PROMPT.md and paste it into Claude Code to complete the migration."
      )
    );
  }

  // ── Collect env vars ──────────────────────────────────────────────────────
  console.log();
  console.log(chalk.bold("  Configure environment variables"));
  console.log(
    chalk.gray(
      "  Press Enter to skip any variable — you can set them up later in apps/web/.env.local\n"
    )
  );

  const stackEnvVars = getEnvVarsForStack(stack);
  const aiEnv = getAIEnvVar(stack.aiProvider);
  const aiMeta = AI_PROVIDERS[stack.aiProvider];

  // Inject AI key before the app URL
  const appUrlIdx = stackEnvVars.findIndex((v) => v.key === "NEXT_PUBLIC_APP_URL");
  if (appUrlIdx !== -1) {
    stackEnvVars.splice(appUrlIdx, 0, {
      key: aiEnv.key,
      prompt: `Enter your ${aiMeta.label} API key`,
      hint: aiMeta.docsUrl,
      secret: true,
    });
  } else {
    stackEnvVars.push({
      key: aiEnv.key,
      prompt: `Enter your ${aiMeta.label} API key`,
      hint: aiMeta.docsUrl,
      secret: true,
    });
  }

  // NextAuth needs AUTH_SECRET
  if (stack.auth === "nextauth") {
    stackEnvVars.unshift(
      {
        key: "AUTH_SECRET",
        prompt: "Enter your NextAuth secret",
        hint: "generate: openssl rand -base64 32",
        secret: true,
      },
      {
        key: "AUTH_GITHUB_ID",
        prompt: "Enter your GitHub OAuth client ID",
        hint: "github.com/settings/developers",
      },
      {
        key: "AUTH_GITHUB_SECRET",
        prompt: "Enter your GitHub OAuth client secret",
        secret: true,
      },
      {
        key: "AUTH_GOOGLE_ID",
        prompt: "Enter your Google OAuth client ID",
        hint: "console.cloud.google.com",
      },
      {
        key: "AUTH_GOOGLE_SECRET",
        prompt: "Enter your Google OAuth client secret",
        secret: true,
      }
    );
  }

  // Supabase needs service role key + DB URL
  if (stack.database === "supabase") {
    const supabaseServiceIdx = stackEnvVars.findIndex((v) => v.key === "SUPABASE_ANON_KEY");
    if (supabaseServiceIdx !== -1) {
      stackEnvVars.splice(supabaseServiceIdx + 1, 0,
        {
          key: "SUPABASE_SERVICE_ROLE_KEY",
          prompt: "Enter your Supabase service role key",
          hint: "Supabase Dashboard → Settings → API",
          secret: true,
        },
        {
          key: "SUPABASE_DB_URL",
          prompt: "Enter your Supabase direct DB URL (for migrations)",
          hint: "Supabase Dashboard → Settings → Database → Connection String → URI",
        }
      );
    }
  }

  const envValues: Record<string, string> = {};

  for (const envVar of stackEnvVars) {
    const label = envVar.hint
      ? `${chalk.white(envVar.prompt)} ${chalk.gray(`(${envVar.hint})`)}`
      : chalk.white(envVar.prompt);

    const response = await prompts(
      {
        type: envVar.secret ? "password" : "text",
        name: "value",
        message: label,
        initial: envVar.default ?? "",
      },
      { onCancel: () => process.exit(0) }
    );

    if (response.value) {
      envValues[envVar.key] = response.value as string;
    }
  }

  // ── Write .env.local ──────────────────────────────────────────────────────
  const envSpinner = ora("Writing .env.local…").start();
  try {
    writeDynamicEnvFile(projectRoot, stack, envValues);
    envSpinner.succeed(
      chalk.green(".env.local written") +
        chalk.gray(" → apps/web/.env.local")
    );
  } catch (err) {
    envSpinner.fail("Failed to write .env.local");
    console.error(err);
  }

  // ── Install dependencies ──────────────────────────────────────────────────
  console.log();
  const { doInstall } = await prompts(
    {
      type: "confirm",
      name: "doInstall",
      message: "Install dependencies now? (pnpm install)",
      initial: true,
    },
    { onCancel: () => process.exit(0) }
  );

  if (doInstall) {
    const installSpinner = ora("Installing dependencies…").start();
    const install = await runCommand("pnpm", ["install"], projectRoot);
    if (install.ok) {
      installSpinner.succeed("Dependencies installed");
    } else {
      installSpinner.warn(
        "pnpm install failed — run " +
          chalk.cyan("pnpm install") +
          " manually."
      );
      if (install.output) console.log(chalk.gray(install.output.slice(0, 400)));
    }
  }

  // ── Database migration ─────────────────────────────────────────────────────
  const dbUrl =
    envValues["DATABASE_URL"] || envValues["SUPABASE_DB_URL"];
  if (dbUrl) {
    console.log();
    const { doMigrate } = await prompts(
      {
        type: "confirm",
        name: "doMigrate",
        message: "Run database migrations now? (pnpm db:migrate)",
        initial: true,
      },
      { onCancel: () => {} }
    );

    if (doMigrate) {
      const migrateSpinner = ora("Running migrations…").start();
      const migrate = await runCommand("pnpm", ["db:migrate"], projectRoot);
      if (migrate.ok) {
        migrateSpinner.succeed("Migrations applied");
      } else {
        migrateSpinner.warn(
          "Migrations failed — run " +
            chalk.cyan("pnpm db:migrate") +
            " manually after verifying your database URL."
        );
        if (migrate.output)
          console.log(chalk.gray(migrate.output.slice(0, 500)));
      }
    }
  }

  // ── Marketing Site Generator ───────────────────────────────────────────────
  console.log();
  const { generateMarketing } = await prompts(
    {
      type: "confirm",
      name: "generateMarketing",
      message: "Generate a custom AI prompt to build your marketing site?",
      initial: true,
    },
    { onCancel: () => process.exit(0) }
  );

  if (generateMarketing) {
    console.log();
    const { saasDescription, saasAudience } = await prompts([
      {
        type: "text",
        name: "saasDescription",
        message: "What does your SaaS do?",
        initial: "An AI tool that writes cover letters for software engineers",
      },
      {
        type: "text",
        name: "saasAudience",
        message: "Who is your target audience?",
        initial: "Junior developers looking for their first job",
      }
    ], { onCancel: () => process.exit(0) });

    const promptContent = `# Marketing Site Generator
Paste this prompt into Claude or Cursor to build your marketing site:

I am building a SaaS that does the following:
Description: ${saasDescription}
Target Audience: ${saasAudience}

You are an expert web designer. I have a Next.js app with Tailwind and shadcn/ui installed at apps/marketing (or apps/web). 
Please generate a high-converting landing page with a hero section, a feature grid, and a pricing table. 
Use a modern dark mode design with a primary color of Emerald Green. Use Framer Motion for subtle fade-in animations on scroll.`;

    fs.writeFileSync(path.join(projectRoot, "MARKETING_PROMPT.md"), promptContent, "utf-8");
    console.log(chalk.green("  ✔ MARKETING_PROMPT.md generated in the project root."));
  }

  // ── Done ──────────────────────────────────────────────────────────────────
  console.log();
  console.log(chalk.green.bold("  ✅ LaunchKit is configured!"));
  console.log();

  printSetupInstructions(stack);

  console.log(chalk.bold("  Start your dev server:"));
  console.log("    " + chalk.cyan("pnpm dev"));
  console.log();
  console.log(
    `  Open ${chalk.underline.blue("http://localhost:3000")} to see your app.`
  );
  console.log();
  console.log(
    `  ${chalk.gray("Docs:")}    ${chalk.underline(LAUNCHKIT_DOCS_URL)}`
  );
  console.log();
}

main().catch((err) => {
  console.error(chalk.red("\nUnexpected error:"), err);
  process.exit(1);
});
