import type { StackConfig } from '@launchkit/config';

/**
 * LaunchKit stack configuration
 * ─────────────────────────────────────────────────────────────────────────────
 * Generated by create-launchkit  →  npx create-launchkit@latest
 *
 * This file is the single source of truth for your stack choices.
 * Re-run the CLI at any time to reconfigure: npx create-launchkit@latest
 *
 * ── Database ──────────────────────────────────────────────────────────────────
 *   neon        Serverless Postgres, branching, generous free tier
 *   supabase    Postgres + auto-APIs + realtime (requires Supabase scaffolder)
 *
 * ── Auth ──────────────────────────────────────────────────────────────────────
 *   clerk       Best DX: pre-built UI, orgs, RBAC  (default)
 *   nextauth    Open source, self-hosted, any OAuth  (requires NextAuth scaffolder)
 *   supabase    Bundled with Supabase DB, row-level security
 *
 * ── Payments ──────────────────────────────────────────────────────────────────
 *   stripe        Most flexible · 2.9% + $0.30
 *   lemonsqueezy  Merchant of Record, handles taxes · 5% + $0.50
 *   paddle        Merchant of Record, global compliance · 5% + $0.50
 *
 * ── AI Provider ───────────────────────────────────────────────────────────────
 *   Direct API:     openai | anthropic | google | perplexity | xai | deepseek | groq | mistral
 *   Cloud-managed:  bedrock (AWS) | vertex (GCP) | azure-openai (Azure)
 *
 * ── Storage ───────────────────────────────────────────────────────────────────
 *   vercel-blob  Zero config on Vercel (default)
 *   s3           AWS S3, Cloudflare R2, MinIO
 *   gcs          Google Cloud Storage
 *   azure-blob   Azure Blob Storage
 *   supabase     Supabase Storage
 *
 * Override at runtime: AI_DEFAULT_MODEL, AI_DEFAULT_PROVIDER, STORAGE_PROVIDER env vars
 */
const config: StackConfig = {
  database: 'neon',
  auth: 'clerk',
  payments: 'stripe',
  deploy: 'vercel',
  email: 'resend',
  analytics: 'posthog',
  realtime: null,
  aiProvider: 'openai',
  storageProvider: 'vercel-blob',
};

export default config;
