/**
 * NextAuth v5 scaffolder
 *
 * Creates 3 foundational auth files for NextAuth v5 (Auth.js):
 *   1. apps/web/lib/auth.ts           — NextAuth configuration
 *   2. apps/web/middleware.ts         — route protection middleware
 *   3. apps/web/app/api/auth/[...nextauth]/route.ts — API route handler
 *
 * Also generates a comprehensive Claude Code prompt for migrating the
 * rest of the app from Clerk to NextAuth v5.
 */

import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";

export interface ScaffoldResult {
  ok: boolean;
  message: string;
}

// ── Template: apps/web/lib/auth.ts ────────────────────────────────────────────

const AUTH_CONFIG_TEMPLATE = `/**
 * NextAuth v5 (Auth.js) configuration
 * Generated by create-launchkit
 *
 * Docs: https://authjs.dev/getting-started
 *
 * Add more providers at https://authjs.dev/getting-started/authentication/oauth
 */
import NextAuth from "next-auth";
import GitHub from "next-auth/providers/github";
import Google from "next-auth/providers/google";
import Resend from "next-auth/providers/resend";
import { DrizzleAdapter } from "@auth/drizzle-adapter";
import { db } from "@launchkit/database";

export const { handlers, signIn, signOut, auth } = NextAuth({
  adapter: DrizzleAdapter(db),
  providers: [
    GitHub({
      clientId: process.env.AUTH_GITHUB_ID,
      clientSecret: process.env.AUTH_GITHUB_SECRET,
    }),
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),
    Resend({
      apiKey: process.env.RESEND_API_KEY,
      from: process.env.EMAIL_FROM ?? "noreply@yourdomain.com",
    }),
  ],
  callbacks: {
    session({ session, user }) {
      session.user.id = user.id;
      return session;
    },
  },
  pages: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    error: "/auth/error",
  },
});
`;

// ── Template: apps/web/middleware.ts ─────────────────────────────────────────

const MIDDLEWARE_TEMPLATE = `/**
 * NextAuth v5 middleware — route protection
 * Generated by create-launchkit
 *
 * Protects all routes under /dashboard, /settings, /portal, /admin.
 * Public routes (landing page, blog, auth pages) are passed through.
 */
import { auth } from "@/lib/auth";
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

const PUBLIC_ROUTES = [
  "/",
  "/pricing",
  "/blog",
  "/changelog",
  "/auth/sign-in",
  "/auth/sign-up",
  "/auth/error",
  "/api/webhooks",
];

export default auth((req) => {
  const { pathname } = req.nextUrl;

  // Allow public routes
  const isPublic = PUBLIC_ROUTES.some(
    (route) => pathname === route || pathname.startsWith(route + "/")
  );
  if (isPublic) return NextResponse.next();

  // Redirect unauthenticated users to sign-in
  if (!req.auth) {
    const signInUrl = new URL("/auth/sign-in", req.url);
    signInUrl.searchParams.set("callbackUrl", pathname);
    return NextResponse.redirect(signInUrl);
  }

  return NextResponse.next();
});

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
`;

// ── Template: apps/web/app/api/auth/[...nextauth]/route.ts ───────────────────

const ROUTE_TEMPLATE = `/**
 * NextAuth v5 API route handler
 * Generated by create-launchkit
 */
import { handlers } from "@/lib/auth";

export const { GET, POST } = handlers;
`;

// ── Claude Code prompt generator ────────────────────────────────────────────

export function generateNextAuthClaudePrompt(): string {
  return `You are helping migrate a Next.js 15 SaaS starter (LaunchKit) from Clerk to NextAuth v5 (Auth.js).

The following 3 files have already been scaffolded:
- apps/web/lib/auth.ts           (NextAuth config with GitHub, Google, Resend providers + DrizzleAdapter)
- apps/web/middleware.ts         (Route protection for /dashboard, /settings, /portal, /admin)
- apps/web/app/api/auth/[...nextauth]/route.ts (API route handler)

Please complete the migration by doing the following:

## 1. Remove Clerk dependencies
- Remove @clerk/nextjs from apps/web/package.json
- Remove all NEXT_PUBLIC_CLERK_* and CLERK_* env references from apps/web/.env.local and .env.example
- Add AUTH_SECRET (run: openssl rand -base64 32), AUTH_GITHUB_ID, AUTH_GITHUB_SECRET, AUTH_GOOGLE_ID, AUTH_GOOGLE_SECRET to .env.local

## 2. Update apps/web/app/layout.tsx
- Remove <ClerkProvider> wrapper
- Remove Clerk imports

## 3. Replace auth hooks throughout the app
Clerk → NextAuth v5 mapping:
- \`import { useAuth } from "@clerk/nextjs"\` → \`import { useSession } from "next-auth/react"\`
- \`const { userId, isSignedIn } = useAuth()\` → \`const { data: session, status } = useSession()\`
- \`const { user } = useUser()\` → \`session?.user\`
- \`<SignedIn>\` → conditional render on \`session?.user\`
- \`<SignedOut>\` → conditional render on \`!session?.user\`
- \`<UserButton />\` → custom UserMenu component using \`session?.user\` + \`signOut()\`
- \`auth().userId\` (server) → \`(await auth()).user?.id\`
- \`currentUser()\` (server) → \`(await auth()).user\`
- \`clerkMiddleware\` → already handled by the scaffolded middleware.ts

## 4. Update sign-in and sign-up pages
Replace Clerk's \`<SignIn />\` and \`<SignUp />\` components with:
- A "Sign in with GitHub" button → calls \`signIn("github")\`
- A "Sign in with Google" button → calls \`signIn("google")\`
- A "Sign in with email" form → calls \`signIn("resend", { email })\`

## 5. Database schema for NextAuth
Add the NextAuth required tables to packages/database/src/schema/auth.ts:
Use the official DrizzleAdapter schema from https://authjs.dev/getting-started/adapters/drizzle

## 6. Install dependencies
In apps/web: add "next-auth@beta", "@auth/drizzle-adapter"
Remove "@clerk/nextjs"

## 7. Test checklist
- [ ] Sign in with GitHub works
- [ ] Sign in with Google works
- [ ] Magic link (email) sign in works
- [ ] Authenticated user ID is available in server components
- [ ] /dashboard redirects to sign-in when logged out
- [ ] Session persists across page reloads

## Important notes
- Use \`import { auth } from "@/lib/auth"\` for server-side session access
- Use \`import { useSession } from "next-auth/react"\` for client-side session access
- Wrap client components that use useSession in <SessionProvider> in layout.tsx
- The \`auth()\` function returns \`{ user: { id, name, email, image } | undefined }\`
`;
}

// ── Main scaffolder ──────────────────────────────────────────────────────────

export function applyNextAuthScaffold(projectRoot: string): ScaffoldResult[] {
  const results: ScaffoldResult[] = [];
  const webRoot = path.join(projectRoot, "apps/web");

  // ── 1. lib/auth.ts ─────────────────────────────────────────────────────────
  const authPath = path.join(webRoot, "lib/auth.ts");
  try {
    // Back up existing file if present
    if (fs.existsSync(authPath)) {
      fs.writeFileSync(authPath + ".clerk.bak", fs.readFileSync(authPath, "utf-8"), "utf-8");
      results.push({ ok: true, message: "Backed up existing lib/auth.ts → lib/auth.ts.clerk.bak" });
    }
    fs.mkdirSync(path.dirname(authPath), { recursive: true });
    fs.writeFileSync(authPath, AUTH_CONFIG_TEMPLATE, "utf-8");
    results.push({ ok: true, message: "Created apps/web/lib/auth.ts" });
  } catch (err) {
    results.push({ ok: false, message: `Failed to write lib/auth.ts: ${err instanceof Error ? err.message : String(err)}` });
  }

  // ── 2. middleware.ts ───────────────────────────────────────────────────────
  const middlewarePath = path.join(webRoot, "middleware.ts");
  try {
    if (fs.existsSync(middlewarePath)) {
      fs.writeFileSync(middlewarePath + ".clerk.bak", fs.readFileSync(middlewarePath, "utf-8"), "utf-8");
      results.push({ ok: true, message: "Backed up existing middleware.ts → middleware.ts.clerk.bak" });
    }
    fs.writeFileSync(middlewarePath, MIDDLEWARE_TEMPLATE, "utf-8");
    results.push({ ok: true, message: "Created apps/web/middleware.ts" });
  } catch (err) {
    results.push({ ok: false, message: `Failed to write middleware.ts: ${err instanceof Error ? err.message : String(err)}` });
  }

  // ── 3. app/api/auth/[...nextauth]/route.ts ────────────────────────────────
  const routeDir = path.join(webRoot, "app/api/auth/[...nextauth]");
  const routePath = path.join(routeDir, "route.ts");
  try {
    fs.mkdirSync(routeDir, { recursive: true });
    fs.writeFileSync(routePath, ROUTE_TEMPLATE, "utf-8");
    results.push({ ok: true, message: "Created apps/web/app/api/auth/[...nextauth]/route.ts" });
  } catch (err) {
    results.push({ ok: false, message: `Failed to write auth route: ${err instanceof Error ? err.message : String(err)}` });
  }

  // ── 4. Write Claude prompt to file ────────────────────────────────────────
  const claudePromptPath = path.join(projectRoot, "NEXTAUTH_MIGRATION_PROMPT.md");
  try {
    fs.writeFileSync(claudePromptPath, generateNextAuthClaudePrompt(), "utf-8");
    results.push({ ok: true, message: "Created NEXTAUTH_MIGRATION_PROMPT.md — paste this into Claude Code to finish the migration" });
  } catch (err) {
    results.push({ ok: false, message: `Failed to write Claude prompt: ${err instanceof Error ? err.message : String(err)}` });
  }

  return results;
}

/** Print NextAuth scaffold results to console */
export function printNextAuthResults(results: ScaffoldResult[]): void {
  for (const result of results) {
    if (result.ok) {
      console.log(`  ${chalk.green("✔")} ${result.message}`);
    } else {
      console.log(`  ${chalk.yellow("⚠")} ${result.message}`);
    }
  }
}
