/**
 * Supabase scaffolder
 *
 * When a user selects Supabase as their database, this patches:
 *   1. packages/database/drizzle.config.ts  — adds connectionString from SUPABASE_DB_URL
 *   2. apps/web/lib/db.ts (if present)      — swaps DATABASE_URL env var reference
 *
 * Supabase uses a standard PostgreSQL connection string, so Drizzle works
 * identically to Neon — only the env var name and URL format differ.
 */

import fs from "node:fs";
import path from "node:path";
import chalk from "chalk";

export interface ScaffoldResult {
  ok: boolean;
  message: string;
}

/**
 * Apply Supabase-specific patches to the LaunchKit project root.
 */
export function applySupabaseScaffold(projectRoot: string): ScaffoldResult[] {
  const results: ScaffoldResult[] = [];

  // ── 1. Patch drizzle.config.ts ─────────────────────────────────────────────
  const drizzleConfigPath = path.join(
    projectRoot,
    "packages/database/drizzle.config.ts"
  );

  if (fs.existsSync(drizzleConfigPath)) {
    try {
      let content = fs.readFileSync(drizzleConfigPath, "utf-8");

      // Replace DATABASE_URL with SUPABASE_DB_URL (Supabase direct connection URL)
      content = content.replace(
        /url:\s*process\.env\.DATABASE_URL!/g,
        "url: process.env.SUPABASE_DB_URL!"
      );

      // Add a comment block at the top if not already present
      if (!content.includes("SUPABASE_DB_URL")) {
        content =
          `// Supabase direct connection URL format:\n` +
          `// postgresql://postgres.[project-ref]:[password]@aws-0-[region].pooler.supabase.com:5432/postgres\n` +
          `// Get from: Supabase Dashboard → Settings → Database → Connection String → URI\n\n` +
          content;
      }

      fs.writeFileSync(drizzleConfigPath, content, "utf-8");
      results.push({
        ok: true,
        message: "Patched packages/database/drizzle.config.ts for Supabase",
      });
    } catch (err) {
      results.push({
        ok: false,
        message: `Failed to patch drizzle.config.ts: ${err instanceof Error ? err.message : String(err)}`,
      });
    }
  } else {
    results.push({
      ok: false,
      message: "drizzle.config.ts not found — skipped",
    });
  }

  // ── 2. Create Supabase client helper ──────────────────────────────────────
  const supabaseClientPath = path.join(
    projectRoot,
    "packages/database/src/supabase.ts"
  );

  if (!fs.existsSync(supabaseClientPath)) {
    try {
      const supabaseClientContent = `/**
 * Supabase client helpers
 * Generated by create-launchkit
 *
 * Uses @supabase/supabase-js for Row Level Security, Realtime, and Storage.
 * For raw SQL queries, use Drizzle ORM via packages/database/src/index.ts.
 */
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.SUPABASE_URL!;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

/** Client-side Supabase client (uses anon key, subject to RLS) */
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Server-side Supabase admin client (uses service role key, bypasses RLS).
 * Only use in server-side code (API routes, server components, server actions).
 */
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});
`;
      fs.writeFileSync(supabaseClientPath, supabaseClientContent, "utf-8");
      results.push({
        ok: true,
        message: "Created packages/database/src/supabase.ts",
      });
    } catch (err) {
      results.push({
        ok: false,
        message: `Failed to create supabase.ts: ${err instanceof Error ? err.message : String(err)}`,
      });
    }
  }

  // ── 3. Print migration note ────────────────────────────────────────────────
  results.push({
    ok: true,
    message: `Supabase setup note: Get your connection string from Supabase Dashboard → Settings → Database → Connection String → URI (use "Direct connection", not pooler, for migrations)`,
  });

  return results;
}

/** Print Supabase scaffold results to console */
export function printSupabaseResults(results: ScaffoldResult[]): void {
  for (const result of results) {
    if (result.ok) {
      console.log(`  ${chalk.green("✔")} ${result.message}`);
    } else {
      console.log(`  ${chalk.yellow("⚠")} ${result.message}`);
    }
  }
}
